// index.js
require('dotenv').config();

const express = require('express');
const cors = require('cors');
const db = require('./config/db_conn');

// ✅ Swagger UI (requires swagger-output.json generated by swagger.js)
const swaggerUi = require('swagger-ui-express');
let swaggerDocument = null;
try {
  swaggerDocument = require('./swagger-output.json');
} catch (e) {
  console.warn('⚠️ swagger-output.json not found. Run: node swagger.js');
}

// ---------------- Routes ----------------
const loginRouter = require('./routes/user');
const collegeRoutes = require('./routes/master_college_api');
const masterUserApi = require('./routes/master_user');
const collegeGroupRoutes = require('./routes/collegeGroup');
const courseRoutes = require('./routes/master_course_api');
const subjectRoutes = require('./routes/master_subject_api');
const studentRoutes = require('./routes/master_student_api');
const teacherRoutes = require('./routes/master_teacher_api');
const masterDeptsRoutes = require('./routes/master_depts');
const collegeAcadYearRoutes = require('./routes/master_acadyear_api');
const subjectCourseRoutes = require('./routes/subject_course_api');
const mastermenuRoutes = require('./routes/menu_master_api');

// ✅ FIX: this must be subject_teacher_api (not master_teacher_api)
const masterSubjectTeacherRoutes = require('./routes/subject_teacher_api');

const userRoleApi = require('./routes/user_role_api');
const MasterRole = require('./routes/master_role_api');
const DailyRoutine = require('./routes/college_daily_routine_api');
const classroomAPI = require('./routes/classroomapi');
const teacherAvailabilityRoutes = require('./routes/teacher_availbility_api');
const collegedailyroutineRoutes = require('./routes/college_daily_routine_api');
const courseofferingRoutes = require('./routes/course_offering_api');
const courseregistrationRoutes = require('./routes/course_registration_api');
const collegeexamroutineRoutes = require('./routes/college_exam_routine_api');
const subjectelecRoutes = require('./routes/subjectelec');
const examroutineRoutes = require('./routes/college_exam_routine_api');
const CollegeAttendenceManager = require('./routes/college_attendance_api');
const EmployeeAttendanceManager = require('./routes/employee_attendance_api');
const ExamResult = require('./routes/college_exam_result_api');
const chartDataApi = require('./routes/chart_data');
const calendarattendance = require('./routes/calendar-attendance');
const cmsFeeStructure = require('./routes/cmsFeeStructure');
const cmsPayment = require('./routes/cmsPayment');
const cmsStudentFeeInvoice = require('./routes/cmsStudentFeeInvoice');
const cmsStuScholarship = require('./routes/cmsStuScholarship');

// New Routes (Version 2)
const teacherDtlsApi = require('./routes/teacher_dtls_api'); // New route
const studentAyRoutes = require('./routes/student_ay'); // New route
const teacherMasterRoutes = require('./routes/teacher_master_bulk_up'); // New route
const examResultApi = require('./routes/exam_result_api'); // New route
const masterFetcher = require('./routes/master_fetcher'); // New route
const smsDeviceRoutes = require('./routes/smsDeviceRoutes'); // New route
const demandLettersRouter = require('./routes/demandLetters'); // New route

const app = express();

// ✅ localhost default PORT
const PORT = process.env.PORT || 9090;

// ✅ detect vercel
const isVercel = !!process.env.VERCEL;

// ✅ compute base url
const BASE_URL =
  process.env.BASE_URL ||
  (isVercel ? 'https://powerangers-zeo.vercel.app' : `http://localhost:${PORT}`);

// ---------------- Middleware ----------------
app.use(cors({
  origin: '*',
  methods: ['GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'OPTIONS'],
  allowedHeaders: ['Content-Type', 'Authorization'],
  credentials: true,
}));

app.use(express.json());

// ✅ Swagger UI route (only if swagger-output.json exists)
if (swaggerDocument) {
  app.use('/docs', swaggerUi.serve, swaggerUi.setup(swaggerDocument));
} else {
  app.get('/docs', (req, res) => {
    res.status(500).json({
      error: 'swagger-output.json not found',
      fix: 'Run: node swagger.js (and commit swagger-output.json for Vercel)',
    });
  });
}

// ---------------- ROUTES ----------------
app.use('/login', loginRouter);
app.use('/master-college', collegeRoutes);
app.use('/api', masterUserApi);
app.use('/api/college-group', collegeGroupRoutes);
app.use('/api/course', courseRoutes);
app.use('/api/subject', subjectRoutes);
app.use('/api/student', studentRoutes);
app.use('/api/teacher', teacherRoutes);
app.use('/api/master-depts', masterDeptsRoutes);
app.use('/api/master-acadyear', collegeAcadYearRoutes);
app.use('/api/subject-course', subjectCourseRoutes);
app.use('/api/menu-master', mastermenuRoutes);
app.use('/api/subject-teacher', masterSubjectTeacherRoutes);
app.use('/api/user-role', userRoleApi);
app.use('/api/master-role', MasterRole);
app.use('/api/daily-routine', DailyRoutine);
app.use('/api/class-room', classroomAPI);
app.use('/api/teacher-availability-manager', teacherAvailabilityRoutes);
app.use('/api/college-daily-routine', collegedailyroutineRoutes);
app.use('/api/course-offering', courseofferingRoutes);
app.use('/api/course-registration', courseregistrationRoutes);
app.use('/api/college-exam-routine', collegeexamroutineRoutes);
app.use('/api/subject-elective', subjectelecRoutes);
app.use('/api/exam-routine-manager', examroutineRoutes);
app.use('/api/CollegeAttendenceManager', CollegeAttendenceManager);
app.use('/api/employee-attendance', EmployeeAttendanceManager);
app.use('/api/exam-result', ExamResult);
app.use('/api/chart-data', chartDataApi);
app.use('/api/calendar-attendance', calendarattendance);
app.use('/api/cms-fee-structure', cmsFeeStructure);
app.use('/api/cms-payments', cmsPayment);
app.use('/api/cms-student-fee-invoice', cmsStudentFeeInvoice);
app.use('/api/cms-stu-scholarship', cmsStuScholarship);

// New Routes (Version 2)
app.use('/api/teacher-dtls', teacherDtlsApi); // New route
app.use('/api/student-ay', studentAyRoutes); // New route
app.use('/api/teacher-master-bulk-up', teacherMasterRoutes); // New route
app.use('/api/exam-result-raw', examResultApi); // New route
app.use('/api/master', masterFetcher); // New route
app.use('/api/sms-device', smsDeviceRoutes); // New route
app.use('/api/demand-letters', demandLettersRouter); // New route

// ---------------- Health-check ----------------
app.get('/', (req, res) => {
  res.json({
    status: 'OK',
    timestamp: new Date().toISOString(),
    base_url: BASE_URL,
    swagger: `${BASE_URL}/docs`,
  });
});

// ✅ Localhost only: start server
async function startLocal() {
  try {
    const { rows } = await db.query('SELECT NOW()');
    console.log('✅ Connected to Postgres at', rows[0].now);

    app.listen(PORT, () => {
      console.log(`🚀 Server running at ${BASE_URL}`);
      console.log(`📚 Swagger Docs at ${BASE_URL}/docs`);
    });
  } catch (err) {
    console.error('❌ Could not connect to Postgres:', err);
    process.exit(1);
  }
}

// ✅ Only run listen() if this file is executed directly (node index.js)
if (!isVercel && require.main === module) {
  startLocal();
}

// ✅ export for Vercel
module.exports = app;
